// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITgN5w7qLC4du9PPa-DuMp8hd1RTrZW8',
    appId: '1:549905827432:web:06fb6156061557c21cdddd',
    messagingSenderId: '549905827432',
    projectId: 'smart-task-manager-a40bd',
    authDomain: 'smart-task-manager-a40bd.firebaseapp.com',
    storageBucket: 'smart-task-manager-a40bd.firebasestorage.app',
    measurementId: 'G-7QBB6GEZ1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYP0Nc96CVDMwQGsHeSRP-CeVZqgTjvUE',
    appId: '1:549905827432:android:56634e94ec6cfcee1cdddd',
    messagingSenderId: '549905827432',
    projectId: 'smart-task-manager-a40bd',
    storageBucket: 'smart-task-manager-a40bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP1ROqIO4fw4SUw1uufMNXmnrKd_8ZZNE',
    appId: '1:549905827432:ios:e31825f09e4168951cdddd',
    messagingSenderId: '549905827432',
    projectId: 'smart-task-manager-a40bd',
    storageBucket: 'smart-task-manager-a40bd.firebasestorage.app',
    iosBundleId: 'com.example.smartTaskManager',
  );
}
